# SPDX-License-Identifier: GPL-2.0

obj-m  := frootspi.o
frootspi-y := frootspi_main.o frootspi_hello.o mcp23s08_driver.o frootspi_pushsw.o

ccflags-y := -std=gnu99 -Werror -Wall -Wno-declaration-after-statement